### PR TITLE
Feat/better way of retrieving teams info

### PR DESCRIPTION
**Pull request by Zelnes**
Following conversation on issuer #5, here is my proposition for Teams version >= 1.5.00.23861 (test of Teams version is not implemented, but if you'd like I could add it, and keep the old version for older releases).

### CODE REVIEW

**Comment by mre** [comment]
Thanks!

When I execute the script if Teams is not open, I get a status code of `0`, which means in a call (?).
I printed the variables and got`current_state: LazyLoadStage` and `current_status: desktop_ips_updated_app_pref`.
Should there be a fallback for unmatched variables in the `switch` statement?
Apart from that I don't know why it matches `*InCall*|*call_accept*)` in my case. 🤔

**Comment by mre** [comment]
Ping @Zelnes 😉

**Comment by Zelnes** [comment]
Sorry, I've been busy these days, and now I feel exhausted because of Teams. I don't have notifications anymore, so I'm using my Windows VM to make calls...
I can't test anymore what I've proposed, I'm very sorry (and I can't even use it anymore, that's the worst)

**Comment by mre** [comment]
That's alright, no worries. Maybe we can revisit this in the future.

**Pull request closed without merging**
